// <auto-generated />
using System;
using AppStorageService.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppStorageService.Infrastructure.Migrations
{
    [DbContext(typeof(MsSqlDbContext))]
    partial class MsSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppStorageService.Infrastructure.Entities.ApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreType")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a23c4d-5e6f-4f8b-9a0c-123456789abc"),
                            CreatedAt = new DateTime(2024, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2024, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TikTok",
                            Status = 2,
                            StoreType = 2,
                            Url = "https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically"
                        },
                        new
                        {
                            Id = new Guid("a2a23c4d-5e6f-4f8b-9a0c-223456789abc"),
                            CreatedAt = new DateTime(2024, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2024, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TikShock",
                            Status = 1,
                            StoreType = 2,
                            Url = "https://play.google.com/store/apps/details?id=com.musically"
                        },
                        new
                        {
                            Id = new Guid("c3a23c4d-5e6f-4f8b-9a0c-323456789abc"),
                            CreatedAt = new DateTime(2024, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2024, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Subway Surfers",
                            Status = 2,
                            StoreType = 1,
                            Url = "https://apps.apple.com/us/app/subway-surfers/id512939461"
                        },
                        new
                        {
                            Id = new Guid("d4a23c4d-5e6f-4f8b-9a0c-423456789abc"),
                            CreatedAt = new DateTime(2024, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2024, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Subway Runners",
                            Status = 1,
                            StoreType = 1,
                            Url = "https://apps.apple.com/us/app/subway-surfers/id51293941"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
